---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 3.3.7
      sourceRef:
        kind: HelmRepository
        name: jenkins-charts
        namespace: flux-system
  values:
    controller:
      image: "jenkins/jenkins"
      tag: "2.277.2-jdk11"
    ingress:
      enabled: true
      annotations: {
        kubernetes.io/ingress.class: nginx
      }
      hostName: "jenkins.${SECRET_DOMAIN}"
