---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gatekeeper-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://open-policy-agent.github.io/gatekeeper/charts
  timeout: 2m
