---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarqube
      version: 9.6.2
      sourceRef:
        kind: HelmRepository
        name: oteemo-charts
        namespace: flux-system
  values:
    image:
      repository: b4bz/homer
      tag: 21.03.2
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "sonarqube.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "homer.${SECRET_DOMAIN}"
