---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: devops
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarqube
      version: 9.6.2
      sourceRef:
        kind: HelmRepository
        name: oteemo-charts
        namespace: flux-system
  values:
    image:
      repository: sonarqube
      tag: 8.5.1-community
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      hosts:
      - name: "sonarqube.${SECRET_DOMAIN}"
        path: /
      # tls:
      # - hosts:
      #   - "homer.${SECRET_DOMAIN}"
