---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gatekeeper
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: gatekeeper-charts
        namespace: flux-system
